apiVersion: v1
kind: Service
metadata:
  name: onlinebookstore-service
  labels:
    app: onlinebookstore
spec:
  selector:
    app: onlinebookstore

  ports:
  - name: http
    port: 8080
    targetPort: 8080

  type: LoadBalancer
